countries = {
    "de": "Germany",
    "ch": "Switzerland",
    "eu": "European Union",
    "al": "Albania",
    "am": "Armenia",
    "at": "Austria",
    "az": "Azerbaijan",
    "ba": "Bosnia-Herzegovina",
    "be": "Belgium",
    "bg": "Bulgaria",
    "by": "Belarus",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "dk": "Denmark",
    "ee": "Estonia",
    "es": "Spain",
    "fi": "Finland",
    "fr": "France",
    "ge": "Georgia",
    "gr": "Greece",
    "hr": "Croatia",
    "hu": "Hungary",
    "ie": "Ireland",
    "it": "Italy",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "md": "Moldova",
    "me": "Montenegro",
    "mk": "North Macedonia",
    "mt": "Malta",
    "nie": "North Ireland",
    "nl": "Netherlands",
    "no": "Norway",
    "pl": "Poland",
    "pt": "Portugal",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "se": "Sweden",
    "sl": "Slovenia",
    "sk": "Slovak Republic",
    "tr": "Turkey",
    "ua": "Ukraine",
    "uk": "United Kingdom",
    "xk": "Kosovo"
}
